apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
stringData:
  access_key: "AKIA......."
  secret_key: "sEbHbjGHB............"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quinto
  labels:
    app: quinto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quinto
  template:
    metadata:
      labels:
        app: quinto
    spec:
      restartPolicy: Always
      containers:
        - name: quinto
          image: docker.io/balamaru/quinto:1.1
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_HOST
              value: "127.0.0.1"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASS
              value: "guest"
            - name: RABBITMQ_QUEUE_DAG
              value: "dag_builder"
            - name: S3_BUCKET
              value: "dags"
            - name: S3_ENDPOINT_URL
              value: "https://s3-url"
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: secret_key
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"